export const COUNTRIES = [
  { name: "Rwanda", code: "RW", dialCode: "+250" },
  { name: "Kenya", code: "KE", dialCode: "+254" },
  { name: "Uganda", code: "UG", dialCode: "+256" },
  { name: "Tanzania", code: "TZ", dialCode: "+255" },
  { name: "Burundi", code: "BI", dialCode: "+257" },
  { name: "Democratic Republic of the Congo", code: "CD", dialCode: "+243" },
  { name: "South Africa", code: "ZA", dialCode: "+27" },
  { name: "Nigeria", code: "NG", dialCode: "+234" },
  { name: "Ghana", code: "GH", dialCode: "+233" },
  { name: "Ethiopia", code: "ET", dialCode: "+251" },
  { name: "Egypt", code: "EG", dialCode: "+20" },
  { name: "United States", code: "US", dialCode: "+1" },
  { name: "United Kingdom", code: "GB", dialCode: "+44" },
  { name: "Canada", code: "CA", dialCode: "+1" },
  { name: "Australia", code: "AU", dialCode: "+61" },
  { name: "France", code: "FR", dialCode: "+33" },
  { name: "Germany", code: "DE", dialCode: "+49" },
  { name: "India", code: "IN", dialCode: "+91" },
  { name: "China", code: "CN", dialCode: "+86" },
  { name: "Japan", code: "JP", dialCode: "+81" },
  { name: "Brazil", code: "BR", dialCode: "+55" },
  { name: "Mexico", code: "MX", dialCode: "+52" },
  // Add more as needed, but this covers major African and global regions
].sort((a, b) => a.name.localeCompare(b.name));
