export const MOCK_MOVIES = [
  { id: "m1", title: "Deadpool & Wolverine", genre: "Action / Comedy", duration: "2h 7m", rating: "R", cover: "https://m.media-amazon.com/images/M/MV5BZTk5ODY0MmQtMzA3Ni00NGY1LThiYzItZThiNjFiNDM4MTM3XkEyXkFqcGc@._V1_.jpg", cinema: "Ster-Kinekor", price: 15, currency: "USD" },
  { id: "m2", title: "Inside Out 2", genre: "Animation / Family", duration: "1h 36m", rating: "PG", cover: "https://m.media-amazon.com/images/M/MV5BYWY3MDE2Y2UtOTE3Zi00MGUzLTg2MTItZjE1ZWVkMGVlODRmXkEyXkFqcGc@._V1_.jpg", cinema: "Canal Olympia", price: 10, currency: "USD" },
  { id: "m3", title: "Dune: Part Two", genre: "Sci-Fi / Action", duration: "2h 46m", rating: "PG-13", cover: "https://m.media-amazon.com/images/M/MV5BNTc0YmQxMjEtODI5MC00NjFiLTlkMWUtOGQ5NjFmYWUyZGJhXkEyXkFqcGc@._V1_.jpg", cinema: "Ster-Kinekor", price: 15, currency: "USD" },
  { id: "m4", title: "Bad Boys: Ride or Die", genre: "Action / Comedy", duration: "1h 55m", rating: "R", cover: "https://m.media-amazon.com/images/M/MV5BZWNjZWUwNDgtYTM4ZC00Zjk0LTg3ZWItNGEyZmVkZTIxZDk0XkEyXkFqcGc@._V1_.jpg", cinema: "Canal Olympia", price: 12, currency: "USD" },
  { id: "m5", title: "A Quiet Place: Day One", genre: "Horror / Thriller", duration: "1h 40m", rating: "PG-13", cover: "https://m.media-amazon.com/images/M/MV5BZmIwMmU4ZWQtOTczZi00ZWEwLThhNjgtZTkwZDRlYmYzNDhkXkEyXkFqcGc@._V1_.jpg", cinema: "Century Cinemax", price: 14, currency: "USD" },
  { id: "m6", title: "Despicable Me 4", genre: "Animation / Comedy", duration: "1h 35m", rating: "PG", cover: "https://m.media-amazon.com/images/M/MV5BNzY0ZTlhYzgtOTgzZC00ZTg2LTk4NTEtZDllM2E2NGE5Njg2XkEyXkFqcGc@._V1_.jpg", cinema: "Century Cinemax", price: 10, currency: "USD" },
  { id: "m7", title: "Twisters", genre: "Action / Thriller", duration: "2h 2m", rating: "PG-13", cover: "https://m.media-amazon.com/images/M/MV5BNjM4MWEwMTEtNTcwYi00ZDI4LWEwMzUtNDMzODBhZmI5MWE1XkEyXkFqcGc@._V1_.jpg", cinema: "Ster-Kinekor", price: 15, currency: "USD" },
  { id: "m8", title: "Gladiator 2", genre: "Action / Drama", duration: "2h 30m", rating: "R", cover: "https://m.media-amazon.com/images/M/MV5BMWYzZTM5ZGQtOGE5My00NmM2LWFlMDEtMGNjYjdmOWM1MzA1XkEyXkFqcGc@._V1_.jpg", cinema: "Canal Olympia", price: 16, currency: "USD" },
  { id: "m9", title: "Furiosa", genre: "Action / Sci-Fi", duration: "2h 28m", rating: "R", cover: "https://images.unsplash.com/photo-1618331835717-801e976710b2?w=800&fit=crop", cinema: "Ster-Kinekor", price: 15, currency: "USD" },
  { id: "m10", title: "Kingdom of the Planet of the Apes", genre: "Sci-Fi / Action", duration: "2h 25m", rating: "PG-13", cover: "https://m.media-amazon.com/images/M/MV5BZDRlZTc3YTItOTk3Yi00NmU4LWFiOGUtNjgwMDZjNjIzNTU1XkEyXkFqcGc@._V1_.jpg", cinema: "Century Cinemax", price: 14, currency: "USD" },
  { id: "m11", title: "Alien: Romulus", genre: "Horror / Sci-Fi", duration: "1h 59m", rating: "R", cover: "https://m.media-amazon.com/images/M/MV5BMDU0NjcwOGQtNjNjOS00NzQ3LWIwM2YtYWVmODZjMzQzN2ExXkEyXkFqcGc@._V1_.jpg", cinema: "Canal Olympia", price: 14, currency: "USD" },
  { id: "m12", title: "Wicked", genre: "Fantasy / Musical", duration: "2h 40m", rating: "PG", cover: "https://m.media-amazon.com/images/M/MV5BOWMwYjYzYmMtMWQ2Ni00NWUwLTg2MzAtYzkzMDBiZDIwOTMwXkEyXkFqcGc@._V1_.jpg", cinema: "Century Cinemax", price: 15, currency: "USD" },
  { id: "m13", title: "Moana 2", genre: "Animation / Adventure", duration: "1h 40m", rating: "PG", cover: "https://m.media-amazon.com/images/M/MV5BMjJkZjE4NjMtNWVjMC00YzIzLWIwYmUtNTBmY2Q0OTQxYTVjXkEyXkFqcGc@._V1_.jpg", cinema: "Ster-Kinekor", price: 12, currency: "USD" },
  { id: "m14", title: "Venom: The Last Dance", genre: "Action / Sci-Fi", duration: "2h 10m", rating: "PG-13", cover: "https://m.media-amazon.com/images/M/MV5BZDMyYWU4NzItZDY0MC00ODE2LTkyYTMtMzNkNDdmYmFhZDg0XkEyXkFqcGc@._V1_.jpg", cinema: "Canal Olympia", price: 15, currency: "USD" },
  { id: "m15", title: "Mufasa: The Lion King", genre: "Adventure / Drama", duration: "2h 0m", rating: "PG", cover: "https://m.media-amazon.com/images/M/MV5BYjBkOWUwODYtYWI3YS00N2I0LWEyYTktOTJjM2YzOTc3ZDNlXkEyXkFqcGc@._V1_.jpg", cinema: "Century Cinemax", price: 13, currency: "USD" },
  { id: "m16", title: "Spider-Man: Beyond the Spider-Verse", genre: "Animation / Action", duration: "2h 20m", rating: "PG", cover: "https://m.media-amazon.com/images/M/MV5BYjkwOWViYzYtMDQzNi00N2U0LWIxYTktNWE2ZDYyM2FhN2M5XkEyXkFqcGc@._V1_.jpg", cinema: "Ster-Kinekor", price: 14, currency: "USD" },
  { id: "m17", title: "Joker: Folie à Deux", genre: "Crime / Drama", duration: "2h 15m", rating: "R", cover: "https://m.media-amazon.com/images/M/MV5BNTRlNmU1NzEtODNkNC00ZGM3LWFmNzQtMjBlMWRiYTcyMGRhXkEyXkFqcGc@._V1_.jpg", cinema: "Canal Olympia", price: 16, currency: "USD" },
  { id: "m18", title: "The Fall Guy", genre: "Action / Comedy", duration: "2h 6m", rating: "PG-13", cover: "https://m.media-amazon.com/images/M/MV5BM2U0MTJiYTItMjNiZS00MzU4LTkxYTAtYTU0ZGY1ODJhMjRhXkEyXkFqcGc@._V1_.jpg", cinema: "Century Cinemax", price: 13, currency: "USD" },
  { id: "m19", title: "Civil War", genre: "Action / Thriller", duration: "1h 49m", rating: "R", cover: "https://m.media-amazon.com/images/M/MV5BYTkzMjc0YzgtY2E0Yi00NDBlLWI0MWUtODY1ZjExMDAyOWZiXkEyXkFqcGc@._V1_.jpg", cinema: "Ster-Kinekor", price: 15, currency: "USD" },
  { id: "m20", title: "Kung Fu Panda 4", genre: "Animation / Action", duration: "1h 34m", rating: "PG", cover: "https://m.media-amazon.com/images/M/MV5BMzJlNGYxYzQtOTg4MC00OTMyLTkwYzMtZDRlNTgwY2YwOWYxXkEyXkFqcGc@._V1_.jpg", cinema: "Canal Olympia", price: 11, currency: "USD" }
];

export const MOCK_MOVIES_MAP: Record<string, any> = MOCK_MOVIES.reduce((acc, movie) => {
  acc[movie.id] = movie;
  return acc;
}, {} as Record<string, any>);
