/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as VenueDesignerRouteImport } from './routes/venue-designer'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrganizersRouteImport } from './routes/organizers'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as MapRouteImport } from './routes/map'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreateEventRouteImport } from './routes/create-event'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TicketDesignerIndexRouteImport } from './routes/ticket-designer.index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as TicketTicketIdRouteImport } from './routes/ticket.$ticketId'
import { Route as TicketDesignerProjectIdRouteImport } from './routes/ticket-designer.$projectId'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as DashboardWorkspacesRouteImport } from './routes/dashboard.workspaces'
import { Route as CommunityPostIdRouteImport } from './routes/community.$postId'
import { Route as BookEventIdRouteImport } from './routes/book.$eventId'
import { Route as DashboardWorkspaceSlugIndexRouteImport } from './routes/dashboard.$workspaceSlug.index'
import { Route as DashboardWorkspaceSlugVenueRentRouteImport } from './routes/dashboard.$workspaceSlug.venue-rent'
import { Route as DashboardWorkspaceSlugEventsIndexRouteImport } from './routes/dashboard.$workspaceSlug.events.index'
import { Route as DashboardWorkspaceSlugVenuesVenueIdRouteImport } from './routes/dashboard.$workspaceSlug.venues.$venueId'
import { Route as DashboardWorkspaceSlugEventsEventIdIndexRouteImport } from './routes/dashboard.$workspaceSlug.events.$eventId.index'
import { Route as DashboardWorkspaceSlugVenuesVenueIdSettingsRouteImport } from './routes/dashboard.$workspaceSlug.venues.$venueId.settings'
import { Route as DashboardWorkspaceSlugVenuesVenueIdOverviewRouteImport } from './routes/dashboard.$workspaceSlug.venues.$venueId.overview'
import { Route as DashboardWorkspaceSlugVenuesVenueIdBookingsRouteImport } from './routes/dashboard.$workspaceSlug.venues.$venueId.bookings'
import { Route as DashboardWorkspaceSlugEventsEventIdVenueRouteImport } from './routes/dashboard.$workspaceSlug.events.$eventId.venue'
import { Route as DashboardWorkspaceSlugEventsEventIdStaffRouteImport } from './routes/dashboard.$workspaceSlug.events.$eventId.staff'
import { Route as DashboardWorkspaceSlugEventsEventIdPlanningRouteImport } from './routes/dashboard.$workspaceSlug.events.$eventId.planning'
import { Route as DashboardWorkspaceSlugEventsEventIdParkingRouteImport } from './routes/dashboard.$workspaceSlug.events.$eventId.parking'
import { Route as DashboardWorkspaceSlugEventsEventIdMerchandiseRouteImport } from './routes/dashboard.$workspaceSlug.events.$eventId.merchandise'
import { Route as DashboardWorkspaceSlugEventsEventIdCustomersRouteImport } from './routes/dashboard.$workspaceSlug.events.$eventId.customers'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const VenueDesignerRoute = VenueDesignerRouteImport.update({
  id: '/venue-designer',
  path: '/venue-designer',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizersRoute = OrganizersRouteImport.update({
  id: '/organizers',
  path: '/organizers',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateEventRoute = CreateEventRouteImport.update({
  id: '/create-event',
  path: '/create-event',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketDesignerIndexRoute = TicketDesignerIndexRouteImport.update({
  id: '/ticket-designer/',
  path: '/ticket-designer/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketTicketIdRoute = TicketTicketIdRouteImport.update({
  id: '/ticket/$ticketId',
  path: '/ticket/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketDesignerProjectIdRoute = TicketDesignerProjectIdRouteImport.update({
  id: '/ticket-designer/$projectId',
  path: '/ticket-designer/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWorkspacesRoute = DashboardWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => DashboardRoute,
} as any)
const CommunityPostIdRoute = CommunityPostIdRouteImport.update({
  id: '/community/$postId',
  path: '/community/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookEventIdRoute = BookEventIdRouteImport.update({
  id: '/book/$eventId',
  path: '/book/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWorkspaceSlugIndexRoute =
  DashboardWorkspaceSlugIndexRouteImport.update({
    id: '/$workspaceSlug/',
    path: '/$workspaceSlug/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWorkspaceSlugVenueRentRoute =
  DashboardWorkspaceSlugVenueRentRouteImport.update({
    id: '/$workspaceSlug/venue-rent',
    path: '/$workspaceSlug/venue-rent',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWorkspaceSlugEventsIndexRoute =
  DashboardWorkspaceSlugEventsIndexRouteImport.update({
    id: '/$workspaceSlug/events/',
    path: '/$workspaceSlug/events/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWorkspaceSlugVenuesVenueIdRoute =
  DashboardWorkspaceSlugVenuesVenueIdRouteImport.update({
    id: '/$workspaceSlug/venues/$venueId',
    path: '/$workspaceSlug/venues/$venueId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWorkspaceSlugEventsEventIdIndexRoute =
  DashboardWorkspaceSlugEventsEventIdIndexRouteImport.update({
    id: '/$workspaceSlug/events/$eventId/',
    path: '/$workspaceSlug/events/$eventId/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWorkspaceSlugVenuesVenueIdSettingsRoute =
  DashboardWorkspaceSlugVenuesVenueIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardWorkspaceSlugVenuesVenueIdRoute,
  } as any)
const DashboardWorkspaceSlugVenuesVenueIdOverviewRoute =
  DashboardWorkspaceSlugVenuesVenueIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => DashboardWorkspaceSlugVenuesVenueIdRoute,
  } as any)
const DashboardWorkspaceSlugVenuesVenueIdBookingsRoute =
  DashboardWorkspaceSlugVenuesVenueIdBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => DashboardWorkspaceSlugVenuesVenueIdRoute,
  } as any)
const DashboardWorkspaceSlugEventsEventIdVenueRoute =
  DashboardWorkspaceSlugEventsEventIdVenueRouteImport.update({
    id: '/$workspaceSlug/events/$eventId/venue',
    path: '/$workspaceSlug/events/$eventId/venue',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWorkspaceSlugEventsEventIdStaffRoute =
  DashboardWorkspaceSlugEventsEventIdStaffRouteImport.update({
    id: '/$workspaceSlug/events/$eventId/staff',
    path: '/$workspaceSlug/events/$eventId/staff',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWorkspaceSlugEventsEventIdPlanningRoute =
  DashboardWorkspaceSlugEventsEventIdPlanningRouteImport.update({
    id: '/$workspaceSlug/events/$eventId/planning',
    path: '/$workspaceSlug/events/$eventId/planning',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWorkspaceSlugEventsEventIdParkingRoute =
  DashboardWorkspaceSlugEventsEventIdParkingRouteImport.update({
    id: '/$workspaceSlug/events/$eventId/parking',
    path: '/$workspaceSlug/events/$eventId/parking',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWorkspaceSlugEventsEventIdMerchandiseRoute =
  DashboardWorkspaceSlugEventsEventIdMerchandiseRouteImport.update({
    id: '/$workspaceSlug/events/$eventId/merchandise',
    path: '/$workspaceSlug/events/$eventId/merchandise',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWorkspaceSlugEventsEventIdCustomersRoute =
  DashboardWorkspaceSlugEventsEventIdCustomersRouteImport.update({
    id: '/$workspaceSlug/events/$eventId/customers',
    path: '/$workspaceSlug/events/$eventId/customers',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/create-event': typeof CreateEventRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/experiences': typeof ExperiencesRoute
  '/explore': typeof ExploreRoute
  '/feed': typeof FeedRoute
  '/map': typeof MapRoute
  '/movies': typeof MoviesRoute
  '/organizers': typeof OrganizersRoute
  '/profile': typeof ProfileRoute
  '/scanner': typeof ScannerRoute
  '/signin': typeof SigninRoute
  '/venue-designer': typeof VenueDesignerRoute
  '/wallet': typeof WalletRoute
  '/book/$eventId': typeof BookEventIdRoute
  '/community/$postId': typeof CommunityPostIdRoute
  '/dashboard/workspaces': typeof DashboardWorkspacesRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/ticket-designer/$projectId': typeof TicketDesignerProjectIdRoute
  '/ticket/$ticketId': typeof TicketTicketIdRoute
  '/events/': typeof EventsIndexRoute
  '/ticket-designer/': typeof TicketDesignerIndexRoute
  '/dashboard/$workspaceSlug/venue-rent': typeof DashboardWorkspaceSlugVenueRentRoute
  '/dashboard/$workspaceSlug/': typeof DashboardWorkspaceSlugIndexRoute
  '/dashboard/$workspaceSlug/venues/$venueId': typeof DashboardWorkspaceSlugVenuesVenueIdRouteWithChildren
  '/dashboard/$workspaceSlug/events/': typeof DashboardWorkspaceSlugEventsIndexRoute
  '/dashboard/$workspaceSlug/events/$eventId/customers': typeof DashboardWorkspaceSlugEventsEventIdCustomersRoute
  '/dashboard/$workspaceSlug/events/$eventId/merchandise': typeof DashboardWorkspaceSlugEventsEventIdMerchandiseRoute
  '/dashboard/$workspaceSlug/events/$eventId/parking': typeof DashboardWorkspaceSlugEventsEventIdParkingRoute
  '/dashboard/$workspaceSlug/events/$eventId/planning': typeof DashboardWorkspaceSlugEventsEventIdPlanningRoute
  '/dashboard/$workspaceSlug/events/$eventId/staff': typeof DashboardWorkspaceSlugEventsEventIdStaffRoute
  '/dashboard/$workspaceSlug/events/$eventId/venue': typeof DashboardWorkspaceSlugEventsEventIdVenueRoute
  '/dashboard/$workspaceSlug/venues/$venueId/bookings': typeof DashboardWorkspaceSlugVenuesVenueIdBookingsRoute
  '/dashboard/$workspaceSlug/venues/$venueId/overview': typeof DashboardWorkspaceSlugVenuesVenueIdOverviewRoute
  '/dashboard/$workspaceSlug/venues/$venueId/settings': typeof DashboardWorkspaceSlugVenuesVenueIdSettingsRoute
  '/dashboard/$workspaceSlug/events/$eventId/': typeof DashboardWorkspaceSlugEventsEventIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/create-event': typeof CreateEventRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/experiences': typeof ExperiencesRoute
  '/explore': typeof ExploreRoute
  '/feed': typeof FeedRoute
  '/map': typeof MapRoute
  '/movies': typeof MoviesRoute
  '/organizers': typeof OrganizersRoute
  '/profile': typeof ProfileRoute
  '/scanner': typeof ScannerRoute
  '/signin': typeof SigninRoute
  '/venue-designer': typeof VenueDesignerRoute
  '/wallet': typeof WalletRoute
  '/book/$eventId': typeof BookEventIdRoute
  '/community/$postId': typeof CommunityPostIdRoute
  '/dashboard/workspaces': typeof DashboardWorkspacesRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/ticket-designer/$projectId': typeof TicketDesignerProjectIdRoute
  '/ticket/$ticketId': typeof TicketTicketIdRoute
  '/events': typeof EventsIndexRoute
  '/ticket-designer': typeof TicketDesignerIndexRoute
  '/dashboard/$workspaceSlug/venue-rent': typeof DashboardWorkspaceSlugVenueRentRoute
  '/dashboard/$workspaceSlug': typeof DashboardWorkspaceSlugIndexRoute
  '/dashboard/$workspaceSlug/venues/$venueId': typeof DashboardWorkspaceSlugVenuesVenueIdRouteWithChildren
  '/dashboard/$workspaceSlug/events': typeof DashboardWorkspaceSlugEventsIndexRoute
  '/dashboard/$workspaceSlug/events/$eventId/customers': typeof DashboardWorkspaceSlugEventsEventIdCustomersRoute
  '/dashboard/$workspaceSlug/events/$eventId/merchandise': typeof DashboardWorkspaceSlugEventsEventIdMerchandiseRoute
  '/dashboard/$workspaceSlug/events/$eventId/parking': typeof DashboardWorkspaceSlugEventsEventIdParkingRoute
  '/dashboard/$workspaceSlug/events/$eventId/planning': typeof DashboardWorkspaceSlugEventsEventIdPlanningRoute
  '/dashboard/$workspaceSlug/events/$eventId/staff': typeof DashboardWorkspaceSlugEventsEventIdStaffRoute
  '/dashboard/$workspaceSlug/events/$eventId/venue': typeof DashboardWorkspaceSlugEventsEventIdVenueRoute
  '/dashboard/$workspaceSlug/venues/$venueId/bookings': typeof DashboardWorkspaceSlugVenuesVenueIdBookingsRoute
  '/dashboard/$workspaceSlug/venues/$venueId/overview': typeof DashboardWorkspaceSlugVenuesVenueIdOverviewRoute
  '/dashboard/$workspaceSlug/venues/$venueId/settings': typeof DashboardWorkspaceSlugVenuesVenueIdSettingsRoute
  '/dashboard/$workspaceSlug/events/$eventId': typeof DashboardWorkspaceSlugEventsEventIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/create-event': typeof CreateEventRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/experiences': typeof ExperiencesRoute
  '/explore': typeof ExploreRoute
  '/feed': typeof FeedRoute
  '/map': typeof MapRoute
  '/movies': typeof MoviesRoute
  '/organizers': typeof OrganizersRoute
  '/profile': typeof ProfileRoute
  '/scanner': typeof ScannerRoute
  '/signin': typeof SigninRoute
  '/venue-designer': typeof VenueDesignerRoute
  '/wallet': typeof WalletRoute
  '/book/$eventId': typeof BookEventIdRoute
  '/community/$postId': typeof CommunityPostIdRoute
  '/dashboard/workspaces': typeof DashboardWorkspacesRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/ticket-designer/$projectId': typeof TicketDesignerProjectIdRoute
  '/ticket/$ticketId': typeof TicketTicketIdRoute
  '/events/': typeof EventsIndexRoute
  '/ticket-designer/': typeof TicketDesignerIndexRoute
  '/dashboard/$workspaceSlug/venue-rent': typeof DashboardWorkspaceSlugVenueRentRoute
  '/dashboard/$workspaceSlug/': typeof DashboardWorkspaceSlugIndexRoute
  '/dashboard/$workspaceSlug/venues/$venueId': typeof DashboardWorkspaceSlugVenuesVenueIdRouteWithChildren
  '/dashboard/$workspaceSlug/events/': typeof DashboardWorkspaceSlugEventsIndexRoute
  '/dashboard/$workspaceSlug/events/$eventId/customers': typeof DashboardWorkspaceSlugEventsEventIdCustomersRoute
  '/dashboard/$workspaceSlug/events/$eventId/merchandise': typeof DashboardWorkspaceSlugEventsEventIdMerchandiseRoute
  '/dashboard/$workspaceSlug/events/$eventId/parking': typeof DashboardWorkspaceSlugEventsEventIdParkingRoute
  '/dashboard/$workspaceSlug/events/$eventId/planning': typeof DashboardWorkspaceSlugEventsEventIdPlanningRoute
  '/dashboard/$workspaceSlug/events/$eventId/staff': typeof DashboardWorkspaceSlugEventsEventIdStaffRoute
  '/dashboard/$workspaceSlug/events/$eventId/venue': typeof DashboardWorkspaceSlugEventsEventIdVenueRoute
  '/dashboard/$workspaceSlug/venues/$venueId/bookings': typeof DashboardWorkspaceSlugVenuesVenueIdBookingsRoute
  '/dashboard/$workspaceSlug/venues/$venueId/overview': typeof DashboardWorkspaceSlugVenuesVenueIdOverviewRoute
  '/dashboard/$workspaceSlug/venues/$venueId/settings': typeof DashboardWorkspaceSlugVenuesVenueIdSettingsRoute
  '/dashboard/$workspaceSlug/events/$eventId/': typeof DashboardWorkspaceSlugEventsEventIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/create-event'
    | '/dashboard'
    | '/experiences'
    | '/explore'
    | '/feed'
    | '/map'
    | '/movies'
    | '/organizers'
    | '/profile'
    | '/scanner'
    | '/signin'
    | '/venue-designer'
    | '/wallet'
    | '/book/$eventId'
    | '/community/$postId'
    | '/dashboard/workspaces'
    | '/events/$eventId'
    | '/ticket-designer/$projectId'
    | '/ticket/$ticketId'
    | '/events/'
    | '/ticket-designer/'
    | '/dashboard/$workspaceSlug/venue-rent'
    | '/dashboard/$workspaceSlug/'
    | '/dashboard/$workspaceSlug/venues/$venueId'
    | '/dashboard/$workspaceSlug/events/'
    | '/dashboard/$workspaceSlug/events/$eventId/customers'
    | '/dashboard/$workspaceSlug/events/$eventId/merchandise'
    | '/dashboard/$workspaceSlug/events/$eventId/parking'
    | '/dashboard/$workspaceSlug/events/$eventId/planning'
    | '/dashboard/$workspaceSlug/events/$eventId/staff'
    | '/dashboard/$workspaceSlug/events/$eventId/venue'
    | '/dashboard/$workspaceSlug/venues/$venueId/bookings'
    | '/dashboard/$workspaceSlug/venues/$venueId/overview'
    | '/dashboard/$workspaceSlug/venues/$venueId/settings'
    | '/dashboard/$workspaceSlug/events/$eventId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/create-event'
    | '/dashboard'
    | '/experiences'
    | '/explore'
    | '/feed'
    | '/map'
    | '/movies'
    | '/organizers'
    | '/profile'
    | '/scanner'
    | '/signin'
    | '/venue-designer'
    | '/wallet'
    | '/book/$eventId'
    | '/community/$postId'
    | '/dashboard/workspaces'
    | '/events/$eventId'
    | '/ticket-designer/$projectId'
    | '/ticket/$ticketId'
    | '/events'
    | '/ticket-designer'
    | '/dashboard/$workspaceSlug/venue-rent'
    | '/dashboard/$workspaceSlug'
    | '/dashboard/$workspaceSlug/venues/$venueId'
    | '/dashboard/$workspaceSlug/events'
    | '/dashboard/$workspaceSlug/events/$eventId/customers'
    | '/dashboard/$workspaceSlug/events/$eventId/merchandise'
    | '/dashboard/$workspaceSlug/events/$eventId/parking'
    | '/dashboard/$workspaceSlug/events/$eventId/planning'
    | '/dashboard/$workspaceSlug/events/$eventId/staff'
    | '/dashboard/$workspaceSlug/events/$eventId/venue'
    | '/dashboard/$workspaceSlug/venues/$venueId/bookings'
    | '/dashboard/$workspaceSlug/venues/$venueId/overview'
    | '/dashboard/$workspaceSlug/venues/$venueId/settings'
    | '/dashboard/$workspaceSlug/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/create-event'
    | '/dashboard'
    | '/experiences'
    | '/explore'
    | '/feed'
    | '/map'
    | '/movies'
    | '/organizers'
    | '/profile'
    | '/scanner'
    | '/signin'
    | '/venue-designer'
    | '/wallet'
    | '/book/$eventId'
    | '/community/$postId'
    | '/dashboard/workspaces'
    | '/events/$eventId'
    | '/ticket-designer/$projectId'
    | '/ticket/$ticketId'
    | '/events/'
    | '/ticket-designer/'
    | '/dashboard/$workspaceSlug/venue-rent'
    | '/dashboard/$workspaceSlug/'
    | '/dashboard/$workspaceSlug/venues/$venueId'
    | '/dashboard/$workspaceSlug/events/'
    | '/dashboard/$workspaceSlug/events/$eventId/customers'
    | '/dashboard/$workspaceSlug/events/$eventId/merchandise'
    | '/dashboard/$workspaceSlug/events/$eventId/parking'
    | '/dashboard/$workspaceSlug/events/$eventId/planning'
    | '/dashboard/$workspaceSlug/events/$eventId/staff'
    | '/dashboard/$workspaceSlug/events/$eventId/venue'
    | '/dashboard/$workspaceSlug/venues/$venueId/bookings'
    | '/dashboard/$workspaceSlug/venues/$venueId/overview'
    | '/dashboard/$workspaceSlug/venues/$venueId/settings'
    | '/dashboard/$workspaceSlug/events/$eventId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  CreateEventRoute: typeof CreateEventRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ExperiencesRoute: typeof ExperiencesRoute
  ExploreRoute: typeof ExploreRoute
  FeedRoute: typeof FeedRoute
  MapRoute: typeof MapRoute
  MoviesRoute: typeof MoviesRoute
  OrganizersRoute: typeof OrganizersRoute
  ProfileRoute: typeof ProfileRoute
  ScannerRoute: typeof ScannerRoute
  SigninRoute: typeof SigninRoute
  VenueDesignerRoute: typeof VenueDesignerRoute
  WalletRoute: typeof WalletRoute
  BookEventIdRoute: typeof BookEventIdRoute
  CommunityPostIdRoute: typeof CommunityPostIdRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  TicketDesignerProjectIdRoute: typeof TicketDesignerProjectIdRoute
  TicketTicketIdRoute: typeof TicketTicketIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
  TicketDesignerIndexRoute: typeof TicketDesignerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venue-designer': {
      id: '/venue-designer'
      path: '/venue-designer'
      fullPath: '/venue-designer'
      preLoaderRoute: typeof VenueDesignerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizers': {
      id: '/organizers'
      path: '/organizers'
      fullPath: '/organizers'
      preLoaderRoute: typeof OrganizersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-event': {
      id: '/create-event'
      path: '/create-event'
      fullPath: '/create-event'
      preLoaderRoute: typeof CreateEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket-designer/': {
      id: '/ticket-designer/'
      path: '/ticket-designer'
      fullPath: '/ticket-designer/'
      preLoaderRoute: typeof TicketDesignerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/$ticketId': {
      id: '/ticket/$ticketId'
      path: '/ticket/$ticketId'
      fullPath: '/ticket/$ticketId'
      preLoaderRoute: typeof TicketTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket-designer/$projectId': {
      id: '/ticket-designer/$projectId'
      path: '/ticket-designer/$projectId'
      fullPath: '/ticket-designer/$projectId'
      preLoaderRoute: typeof TicketDesignerProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/workspaces': {
      id: '/dashboard/workspaces'
      path: '/workspaces'
      fullPath: '/dashboard/workspaces'
      preLoaderRoute: typeof DashboardWorkspacesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/community/$postId': {
      id: '/community/$postId'
      path: '/community/$postId'
      fullPath: '/community/$postId'
      preLoaderRoute: typeof CommunityPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$eventId': {
      id: '/book/$eventId'
      path: '/book/$eventId'
      fullPath: '/book/$eventId'
      preLoaderRoute: typeof BookEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$workspaceSlug/': {
      id: '/dashboard/$workspaceSlug/'
      path: '/$workspaceSlug'
      fullPath: '/dashboard/$workspaceSlug/'
      preLoaderRoute: typeof DashboardWorkspaceSlugIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$workspaceSlug/venue-rent': {
      id: '/dashboard/$workspaceSlug/venue-rent'
      path: '/$workspaceSlug/venue-rent'
      fullPath: '/dashboard/$workspaceSlug/venue-rent'
      preLoaderRoute: typeof DashboardWorkspaceSlugVenueRentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$workspaceSlug/events/': {
      id: '/dashboard/$workspaceSlug/events/'
      path: '/$workspaceSlug/events'
      fullPath: '/dashboard/$workspaceSlug/events/'
      preLoaderRoute: typeof DashboardWorkspaceSlugEventsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$workspaceSlug/venues/$venueId': {
      id: '/dashboard/$workspaceSlug/venues/$venueId'
      path: '/$workspaceSlug/venues/$venueId'
      fullPath: '/dashboard/$workspaceSlug/venues/$venueId'
      preLoaderRoute: typeof DashboardWorkspaceSlugVenuesVenueIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$workspaceSlug/events/$eventId/': {
      id: '/dashboard/$workspaceSlug/events/$eventId/'
      path: '/$workspaceSlug/events/$eventId'
      fullPath: '/dashboard/$workspaceSlug/events/$eventId/'
      preLoaderRoute: typeof DashboardWorkspaceSlugEventsEventIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$workspaceSlug/venues/$venueId/settings': {
      id: '/dashboard/$workspaceSlug/venues/$venueId/settings'
      path: '/settings'
      fullPath: '/dashboard/$workspaceSlug/venues/$venueId/settings'
      preLoaderRoute: typeof DashboardWorkspaceSlugVenuesVenueIdSettingsRouteImport
      parentRoute: typeof DashboardWorkspaceSlugVenuesVenueIdRoute
    }
    '/dashboard/$workspaceSlug/venues/$venueId/overview': {
      id: '/dashboard/$workspaceSlug/venues/$venueId/overview'
      path: '/overview'
      fullPath: '/dashboard/$workspaceSlug/venues/$venueId/overview'
      preLoaderRoute: typeof DashboardWorkspaceSlugVenuesVenueIdOverviewRouteImport
      parentRoute: typeof DashboardWorkspaceSlugVenuesVenueIdRoute
    }
    '/dashboard/$workspaceSlug/venues/$venueId/bookings': {
      id: '/dashboard/$workspaceSlug/venues/$venueId/bookings'
      path: '/bookings'
      fullPath: '/dashboard/$workspaceSlug/venues/$venueId/bookings'
      preLoaderRoute: typeof DashboardWorkspaceSlugVenuesVenueIdBookingsRouteImport
      parentRoute: typeof DashboardWorkspaceSlugVenuesVenueIdRoute
    }
    '/dashboard/$workspaceSlug/events/$eventId/venue': {
      id: '/dashboard/$workspaceSlug/events/$eventId/venue'
      path: '/$workspaceSlug/events/$eventId/venue'
      fullPath: '/dashboard/$workspaceSlug/events/$eventId/venue'
      preLoaderRoute: typeof DashboardWorkspaceSlugEventsEventIdVenueRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$workspaceSlug/events/$eventId/staff': {
      id: '/dashboard/$workspaceSlug/events/$eventId/staff'
      path: '/$workspaceSlug/events/$eventId/staff'
      fullPath: '/dashboard/$workspaceSlug/events/$eventId/staff'
      preLoaderRoute: typeof DashboardWorkspaceSlugEventsEventIdStaffRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$workspaceSlug/events/$eventId/planning': {
      id: '/dashboard/$workspaceSlug/events/$eventId/planning'
      path: '/$workspaceSlug/events/$eventId/planning'
      fullPath: '/dashboard/$workspaceSlug/events/$eventId/planning'
      preLoaderRoute: typeof DashboardWorkspaceSlugEventsEventIdPlanningRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$workspaceSlug/events/$eventId/parking': {
      id: '/dashboard/$workspaceSlug/events/$eventId/parking'
      path: '/$workspaceSlug/events/$eventId/parking'
      fullPath: '/dashboard/$workspaceSlug/events/$eventId/parking'
      preLoaderRoute: typeof DashboardWorkspaceSlugEventsEventIdParkingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$workspaceSlug/events/$eventId/merchandise': {
      id: '/dashboard/$workspaceSlug/events/$eventId/merchandise'
      path: '/$workspaceSlug/events/$eventId/merchandise'
      fullPath: '/dashboard/$workspaceSlug/events/$eventId/merchandise'
      preLoaderRoute: typeof DashboardWorkspaceSlugEventsEventIdMerchandiseRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$workspaceSlug/events/$eventId/customers': {
      id: '/dashboard/$workspaceSlug/events/$eventId/customers'
      path: '/$workspaceSlug/events/$eventId/customers'
      fullPath: '/dashboard/$workspaceSlug/events/$eventId/customers'
      preLoaderRoute: typeof DashboardWorkspaceSlugEventsEventIdCustomersRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardWorkspaceSlugVenuesVenueIdRouteChildren {
  DashboardWorkspaceSlugVenuesVenueIdBookingsRoute: typeof DashboardWorkspaceSlugVenuesVenueIdBookingsRoute
  DashboardWorkspaceSlugVenuesVenueIdOverviewRoute: typeof DashboardWorkspaceSlugVenuesVenueIdOverviewRoute
  DashboardWorkspaceSlugVenuesVenueIdSettingsRoute: typeof DashboardWorkspaceSlugVenuesVenueIdSettingsRoute
}

const DashboardWorkspaceSlugVenuesVenueIdRouteChildren: DashboardWorkspaceSlugVenuesVenueIdRouteChildren =
  {
    DashboardWorkspaceSlugVenuesVenueIdBookingsRoute:
      DashboardWorkspaceSlugVenuesVenueIdBookingsRoute,
    DashboardWorkspaceSlugVenuesVenueIdOverviewRoute:
      DashboardWorkspaceSlugVenuesVenueIdOverviewRoute,
    DashboardWorkspaceSlugVenuesVenueIdSettingsRoute:
      DashboardWorkspaceSlugVenuesVenueIdSettingsRoute,
  }

const DashboardWorkspaceSlugVenuesVenueIdRouteWithChildren =
  DashboardWorkspaceSlugVenuesVenueIdRoute._addFileChildren(
    DashboardWorkspaceSlugVenuesVenueIdRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardWorkspacesRoute: typeof DashboardWorkspacesRoute
  DashboardWorkspaceSlugVenueRentRoute: typeof DashboardWorkspaceSlugVenueRentRoute
  DashboardWorkspaceSlugIndexRoute: typeof DashboardWorkspaceSlugIndexRoute
  DashboardWorkspaceSlugVenuesVenueIdRoute: typeof DashboardWorkspaceSlugVenuesVenueIdRouteWithChildren
  DashboardWorkspaceSlugEventsIndexRoute: typeof DashboardWorkspaceSlugEventsIndexRoute
  DashboardWorkspaceSlugEventsEventIdCustomersRoute: typeof DashboardWorkspaceSlugEventsEventIdCustomersRoute
  DashboardWorkspaceSlugEventsEventIdMerchandiseRoute: typeof DashboardWorkspaceSlugEventsEventIdMerchandiseRoute
  DashboardWorkspaceSlugEventsEventIdParkingRoute: typeof DashboardWorkspaceSlugEventsEventIdParkingRoute
  DashboardWorkspaceSlugEventsEventIdPlanningRoute: typeof DashboardWorkspaceSlugEventsEventIdPlanningRoute
  DashboardWorkspaceSlugEventsEventIdStaffRoute: typeof DashboardWorkspaceSlugEventsEventIdStaffRoute
  DashboardWorkspaceSlugEventsEventIdVenueRoute: typeof DashboardWorkspaceSlugEventsEventIdVenueRoute
  DashboardWorkspaceSlugEventsEventIdIndexRoute: typeof DashboardWorkspaceSlugEventsEventIdIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardWorkspacesRoute: DashboardWorkspacesRoute,
  DashboardWorkspaceSlugVenueRentRoute: DashboardWorkspaceSlugVenueRentRoute,
  DashboardWorkspaceSlugIndexRoute: DashboardWorkspaceSlugIndexRoute,
  DashboardWorkspaceSlugVenuesVenueIdRoute:
    DashboardWorkspaceSlugVenuesVenueIdRouteWithChildren,
  DashboardWorkspaceSlugEventsIndexRoute:
    DashboardWorkspaceSlugEventsIndexRoute,
  DashboardWorkspaceSlugEventsEventIdCustomersRoute:
    DashboardWorkspaceSlugEventsEventIdCustomersRoute,
  DashboardWorkspaceSlugEventsEventIdMerchandiseRoute:
    DashboardWorkspaceSlugEventsEventIdMerchandiseRoute,
  DashboardWorkspaceSlugEventsEventIdParkingRoute:
    DashboardWorkspaceSlugEventsEventIdParkingRoute,
  DashboardWorkspaceSlugEventsEventIdPlanningRoute:
    DashboardWorkspaceSlugEventsEventIdPlanningRoute,
  DashboardWorkspaceSlugEventsEventIdStaffRoute:
    DashboardWorkspaceSlugEventsEventIdStaffRoute,
  DashboardWorkspaceSlugEventsEventIdVenueRoute:
    DashboardWorkspaceSlugEventsEventIdVenueRoute,
  DashboardWorkspaceSlugEventsEventIdIndexRoute:
    DashboardWorkspaceSlugEventsEventIdIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  CreateEventRoute: CreateEventRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ExperiencesRoute: ExperiencesRoute,
  ExploreRoute: ExploreRoute,
  FeedRoute: FeedRoute,
  MapRoute: MapRoute,
  MoviesRoute: MoviesRoute,
  OrganizersRoute: OrganizersRoute,
  ProfileRoute: ProfileRoute,
  ScannerRoute: ScannerRoute,
  SigninRoute: SigninRoute,
  VenueDesignerRoute: VenueDesignerRoute,
  WalletRoute: WalletRoute,
  BookEventIdRoute: BookEventIdRoute,
  CommunityPostIdRoute: CommunityPostIdRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  TicketDesignerProjectIdRoute: TicketDesignerProjectIdRoute,
  TicketTicketIdRoute: TicketTicketIdRoute,
  EventsIndexRoute: EventsIndexRoute,
  TicketDesignerIndexRoute: TicketDesignerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
