export interface SettingsProps {
  user: any;
  refresh: () => void;
  theme: string;
  setTheme: (t: any) => void;
  navigate: any;
  activeModal: string | null;
  setActiveModal: (m: string | null) => void;
  desktopTab: string;
  setDesktopTab: (t: string) => void;
  general: any;
  setGeneral: (g: any) => void;
  isUpdatingGeneral: boolean;
  isOtpStep: boolean;
  setIsOtpStep: (s: boolean) => void;
  generatedOtp: string;
  otpInput: string;
  setOtpInput: (s: string) => void;
  deleteConfirmHandle: string;
  setDeleteConfirmHandle: (s: string) => void;
  isDeletingAccount: boolean;
  password: "";
  setPassword: (s: string) => void;
  confirmPassword: "";
  setConfirmPassword: (s: string) => void;
  isUpdatingPassword: boolean;
  selectedStyle: string;
  setSelectedStyle: (s: string) => void;
  seed: string;
  setSeed: (s: string) => void;
  isUpdatingAvatar: boolean;
  stagedAvatar: string | null;
  setStagedAvatar: (s: string | null) => void;
  generatedAvatars: string[];
  selectedInterests: string[];
  setSelectedInterests: (i: any) => void;
  initialInterests: string[];
  isUpdatingInterests: boolean;
  
  handleUpdateGeneral: (e: any) => void;
  handleUpdatePassword: (e: any) => void;
  handleSelectAvatar: (url: string) => void;
  handleUpdateInterests: () => void;
  handleDeleteAccount: () => void;
  getModalTitle: () => string;
  DESKTOP_TABS: any[];
  COUNTRIES: any[];
  INTEREST_OPTIONS: any[];
  AVATAR_STYLES: any[];
}
